import type { State, Item } from "./types";
const products = [
  [
    "water",
    "น้ำดื่ม",
    "Drinking water · 600 ml",
    7,
    48,
    "8850000000011",
    "drinks",
    "/products/water.jpg",
  ],
  [
    "milk",
    "นมจืด",
    "Fresh milk · 200 ml",
    12,
    24,
    "8850000000028",
    "drinks",
    "/products/milk.jpg",
  ],
  [
    "juice",
    "น้ำส้ม",
    "Orange juice · 200 ml",
    15,
    18,
    "8850000000035",
    "drinks",
    "/products/juice.jpg",
  ],
  [
    "chips",
    "มันฝรั่งทอด",
    "Potato chips · original",
    20,
    30,
    "8850000000042",
    "snacks",
    "/products/chips.jpg",
  ],
  [
    "cookies",
    "คุกกี้ช็อกโกแลต",
    "Chocolate chip cookies",
    10,
    36,
    "8850000000059",
    "snacks",
    "/products/cookies.jpg",
  ],
  [
    "noodles",
    "บะหมี่กึ่งสำเร็จรูป",
    "Instant noodles · cup",
    18,
    8,
    "8850000000066",
    "food",
    "",
  ],
  [
    "pencil",
    "ดินสอ 2B",
    "Pencil · single",
    5,
    40,
    "8850000000073",
    "supplies",
    "",
  ],
  [
    "notebook",
    "สมุดบันทึก",
    "Notebook · 40 pages",
    15,
    0,
    "8850000000080",
    "supplies",
    "",
  ],
] as const;
export function initialState(): State {
  return {
    items: products.map(
      ([id, name, subtitle, price, stock, barcode, category, image]) => ({
        id,
        name,
        subtitle,
        price,
        stock,
        barcode,
        category,
        image,
        reorderLevel: 10,
        active: true,
      }),
    ) as Item[],
    transactions: [],
    settings: { cooperativeBalance: 0, dailyTarget: 500, storeOpen: true },
    budget: [],
    attempts: {},
    users: [],
    sessions: [],
  };
}
